# Generated by Django 4.0.4 on 2022-06-11 17:33

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('price_pw', models.IntegerField()),
                ('price_pm', models.IntegerField()),
                ('location', models.TextField(max_length=250)),
                ('property_type', models.TextField(max_length=250)),
                ('url', models.URLField()),
            ],
        ),
    ]
