# Generated by Django 4.0.4 on 2022-06-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_pw', models.IntegerField()),
                ('price_pm', models.IntegerField()),
                ('location', models.TextField(max_length=250)),
                ('property_type', models.TextField(max_length=250)),
            ],
        ),
    ]
